# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoChatApp
	pod 'Starscream', '~> 4.0.3'
	pod 'GoogleWebRTC'
end
